### ISSUE TITLE
Protobuf compiler required after libp2p upgrade

### ISSUE THREAD

**Issue by tiainen** [pyrsia/pyrsia-integration-tests#19]
When the version of the `libp2p` crate is updated to `0.50.0`, building the pyrsia node will require the protobuf compiler to be installed. This is handled in PR https://github.com/pyrsia/pyrsia/pull/1348. Since the integration tests also build the node, we'll need to install `protoc` in the docker container where the tests are run.

**Comment by dasmanas** [comment]
Does that mean to include protobuf-compiler like https://github.com/pyrsia/pyrsia/blob/14e1b5ecf2c90fedb949bca54aa47759436df1c4/installers/docker/local_code_coverage/Dockerfile#L4

**Comment by tiainen** [comment]
That is exactly what I meant. The associated PR pyrsia/pyrsia-integration-tests#20 is ready for review.
